version: '3.8'

services:
  service_10k:
    build:
      context: ./service_10k
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/code/app/logs
    networks:
      - app-network

  service_twitter:
    build:
      context: ./service_twitter
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - ./logs:/code/app/logs
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - service_10k
      - service_twitter

networks:
  app-network:
    driver: bridge